# Generated by Django 3.1.2 on 2020-10-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_interest_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='trend',
            name='type',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='trend',
            name='site',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
